name: Tests

on:
  pull_request:
    branches: '*'

  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch, tag or SHA to release from'
        required: true
        default: 'master'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.6]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install test dependencies
        run: python -m pip install pytest

      - name: Install current version of the clamd package
        run: python -m pip install -e .

      - name: Install and update clamav engine
        run: |
          sudo apt update
          sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs --yes
          sudo systemctl stop clamav-freshclam.service
          sudo freshclam --verbose
          sudo systemctl restart clamav-daemon.service

      - name: Wait for 25 seconds until clamd socket becomes available
        run: |
          secs=25
          while [[ $secs -gt 0 ]] && ! [[ -f "/var/run/clamav/clamd.ctl" ]];
          do
              echo -ne "$secs\033[0K\r"
              sleep 1
              : $((secs--))
          done

      - name: Run unit tests
        run: pytest
